My_list = [2, 1, 3, 4, 5, 6]
My_list.sort()
print(My_list)
My_list.append(20)
print(My_list)
My_list.extend([0])
print(My_list)
My_list.sort()
print(My_list)
number = My_list.pop()
print(number)
print(My_list)